annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Upgraded `mariadb` chart dependency to version `10.2.0`.
    - kind: changed
      description: Upgraded `postgresql` chart dependency to version `10.14.4`.
apiVersion: v2
appVersion: v4.3.1
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 10.14.4
- condition: mariadb.enabled
  name: mariadb
  repository: https://charts.bitnami.com/bitnami
  version: 10.2.0
description: PowerDNS is a DNS server, written in C++ and licensed under the GPL.
  It runs on most Unix derivatives. PowerDNS features a large number of different
  backends ranging from simple BIND style zonefiles to relational databases and load
  balancing/failover algorithms. A DNS recursor is provided as a separate program.
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/powerdns
icon: https://avatars.githubusercontent.com/u/1282630?s=200&v=4
maintainers:
- email: ryan@ryanholt.net
  name: carpenike
name: powerdns
sources:
- http://www.github.com/PowerDNS/
version: 4.0.0
